(1) 블록 목록 조회
	WITH tb0 AS (
	    SELECT *
	    FROM pm07_a10
	    WHERE mfg_ind = '1'
	    AND lrgcod  = 'PA'
	    AND midcod  = '20'
	    AND dtlcod <> '_'
	)
	SELECT
	    T1.SHIP_NO, T1.BLOCK,
	    SUBSTR(XMLAGG(XMLELEMENT(x,';',wgs84_longi||','||wgs84_lati) ORDER BY seqno).EXTRACT('//text()'), 2) ctipointa
	FROM (
	    SELECT
	        T1.SHIP_NO, T1.BLOCK, T1.SEQNO, T2.JIBUN, T2.MFG_IND,
	        max(T1.WGS84_LONGI) WGS84_LONGI,
	        max(T1.WGS84_LATI) WGS84_LATI
	    FROM PM07_D30 T1
	    JOIN PM07_D20 T2 ON T1.SHIP_NO = T2.SHIP_NO AND T1.BLOCK = T2.BLOCK AND NOT (T1.WGS84_LONGI IS NULL AND T1.WGS84_LATI IS NULL)
	    JOIN PM07_A70 T3 ON T2.JIBUN = T3.JIBUN AND T2.MFG_IND = T3.MFG_IND AND T3.YNUSE = 'Y'
	    JOIN PM07_E30 T4 ON T3.JBNGRP = T4.JBNGRP AND T4.AREAGRP = 'A100'
	    JOIN PM07_A75 T5 ON T3.JIBUN = T5.JIBUN AND T3.MFG_IND = T5.MFG_IND
	    JOIN PM07_E10 T6 ON T4.AREAGRP = T6.AREAGRP
	    WHERE T2.CURGBN = 'P'
	    AND (T6.MFG_IND1 = '1' OR T6.MFG_IND2 = '1')
	    AND (T6.MFG_IND1 = T3.MFG_IND OR T6.MFG_IND2 = T3.MFG_IND)
	    AND (CASE WHEN T2.MFG_IND <> 'C' AND (T1.WGS84_LONGI IS NULL OR T1.WGS84_LATI IS NULL) THEN 'X' ELSE 'O' END) = 'O'
	    GROUP BY T1.SHIP_NO, T1.BLOCK, T1.SEQNO, T2.JIBUN, T2.MFG_IND
	) T1
	GROUP BY T1.SHIP_NO, T1.BLOCK

(2)